# Generated by Django 3.2.5 on 2021-07-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennistable',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размеры упаковки'),
        ),
    ]
