# Generated by Django 3.2.5 on 2021-08-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210805_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennistable',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='treadmill',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='weight',
            field=models.CharField(max_length=255, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='tennistable',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tennistable',
            name='weight',
            field=models.CharField(max_length=255, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='treadmill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='treadmill',
            name='weight',
            field=models.CharField(max_length=255, verbose_name='Вес'),
        ),
    ]
