# Generated by Django 3.2.5 on 2021-08-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210805_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennistable',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='treadmill',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='ball',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tennistable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='treadmill',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
    ]
