# Generated by Django 3.2.5 on 2021-08-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210805_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treadmill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
    ]
