# Generated by Django 3.2.5 on 2021-08-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_treadmill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tennistable',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='treadmill',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='category',
            field=models.ForeignKey(blank=True, default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='tennistable',
            name='category',
            field=models.ForeignKey(blank=True, default=2, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tennistable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='treadmill',
            name='category',
            field=models.ForeignKey(blank=True, default=3, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='treadmill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
