# Generated by Django 3.2.5 on 2021-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210809_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ball',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='tennistable',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='treadmill',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='ball',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='ball',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='tennistable',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='tennistable',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='treadmill',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AddField(
            model_name='treadmill',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
    ]
