# Generated by Django 3.2.5 on 2021-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210809_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
