# Generated by Django 3.2.5 on 2021-08-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_cart_anonymous_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
    ]
