# Generated by Django 3.2.5 on 2021-08-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_cartproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='anonymous_user',
        ),
    ]
