# Generated by Django 3.2.5 on 2021-08-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('mainapp', '0018_auto_20210821_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCustomer',
        ),
    ]
