# Generated by Django 3.2.5 on 2021-08-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0019_delete_newcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='sub_image_1',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='sub_image_2',
        ),
        migrations.RemoveField(
            model_name='tennistable',
            name='sub_image_1',
        ),
        migrations.RemoveField(
            model_name='tennistable',
            name='sub_image_2',
        ),
        migrations.RemoveField(
            model_name='treadmill',
            name='sub_image_1',
        ),
        migrations.RemoveField(
            model_name='treadmill',
            name='sub_image_2',
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
